# Generated by Django 4.1.7 on 2023-04-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(max_length=255)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens_produtos/%Y/%m/')),
                ('slug', models.SlugField(unique=True)),
                ('preco', models.FloatField()),
                ('preco_pomocional', models.FloatField(default=0)),
                ('tipo', models.CharField(choices=[('V', 'Variavel'), ('S', 'Simples')], default='V', max_length=1)),
            ],
        ),
    ]
